version: '0.4.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
services:
- mssql2017
- postgresql
nuget:
  disable_publish_on_pr: true  
before_build:
  - cmd: dotnet --version
  - choco install codecov
  - cmd: echo %postgres_connection%
  - cmd: echo %sql_connection%
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test ./tests/MinimigTests.csproj /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit"
after_test:
  - codecov -f "./tests/coverage.netcoreapp2.1.xml" -t $(codecov_token)
  - codecov -f "./tests/coverage.netcoreapp3.1.xml" -t $(codecov_token)
environment:
  postgres_connection:
    secure: YW0OmwTb/Q3byjNiJzsXc4UN5JJRbI3uYItkJPLB3F2d/rxamWDJbfwQ7aI0FEfQ6YYPoafFf4Of9o0bYo1ls8w8DzT1xx9RIBZ5nSdnUR9yFIHo2imYYHD+w+4JMGHh
  sql_connection:
    secure: IDN3XLRl6oFBvm1ql3udiL77wdDcn+zDJHi3fV0rHByKD87DyilxrR78kvuhroAqEm57nDSMDt4/gjWhkcV6Z6+1hazXfVXk8JAtzSVSjMg=
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/minimig/api/v2/package
  on:
    branch: develop
    appveyor_repo_tag: true
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
