version: '0.6.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
  - cmd: net start MSSQL$SQL2019
configuration:
  - Release
services:
- postgresql
nuget:
  disable_publish_on_pr: true  
before_build:
  - cmd: dotnet --version
  - choco install codecov
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test ./tests/MinimigTests.csproj /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit"
after_test:
  - codecov -f "./tests/coverage.netcoreapp3.1.xml" -t $(codecov_token)
environment:
  postgres_connection:
    secure: YW0OmwTb/Q3byjNiJzsXc4UN5JJRbI3uYItkJPLB3F2d/rxamWDJbfwQ7aI0FEfQ6YYPoafFf4Of9o0bYo1ls8w8DzT1xx9RIBZ5nSdnUR9yFIHo2imYYHD+w+4JMGHh
  sql_connection:
    secure: IDN3XLRl6oFBvm1ql3udiAXGfdZmk7Ve+EkWfyD6hbANvKgm39j2m+LOtrOXdlBn0l7uh/TENf51P5bNgS/Nn7OoKwXeu1lcMNvLUzx2+MA=
  codecov_token:
    secure: lUmWvr1PcJnFJ7tR5/Y+fpuIPkc0L822Dh/NQy6EACQHZa/KY//Vwkap4lZg3yAN
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/minimig/api/v2/package
  on:
    branch: develop
    appveyor_repo_tag: true
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
