version: '0.11.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
services:
  - docker
nuget:
  disable_publish_on_pr: true
install:
- ps: |
    Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
    & $env:temp\dotnet-install.ps1 -Architecture x64 -Version '8.0.100' -InstallDir "$env:ProgramFiles\dotnet"
before_build:
  - cmd: dotnet --version
  - docker-compose -f .docker\docker-compose.yml up -d
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test ./tests/MinimigTests.csproj /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit" /p:AltCoverAssemblyFilter="testhost|Microsoft"
after_test:
  - codecov -f "./tests/coverage.net8.0.xml" -t $(codecov_token)
environment:
  codecov_token:
    secure: lUmWvr1PcJnFJ7tR5/Y+fpuIPkc0L822Dh/NQy6EACQHZa/KY//Vwkap4lZg3yAN
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/minimig/api/v2/package
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
