version: '0.2.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
  - develop
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
services:
- mssql2017
nuget:
  disable_publish_on_pr: true  
before_build:
  - cmd: dotnet --version
  - choco install codecov  
build_script:
  - cmd: dotnet build . -v quiet
test_script:
  - cmd: dotnet test ./tests/MinimigTests.csproj /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="xunit"
after_test:
  - codecov -f "./tests/coverage.xml" -t $(codecov_token)
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/minimig/api/v2/package
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: 6xhHSsDvB9arsrSDLuynnbxaVS+BwaoJU96RfQenc5FOnUYvP8SHM6kbvrmpvja2
  skip_symbols: true
